const AppConstants = {
  ACTIVITY_THEME_URL: 'http://api.itianluo.cn/feed_activity_element',
  ACTIVITY_FOLLOWERS_URL: 'http://api.itianluo.cn/feed_activity_signup_list',
  ACTIVITY_DETAILS_URL: 'http://api.itianluo.cn/feed_activity_get_h5',
  ACTIVITY_COMMENTS_URL: 'http://api.itianluo.cn/feed_activity_bbs_list',
  ACTIVITY_COMMENTS_LIKE_URL: 'http://api.itianluo.cn/feed_cancel_like',
  ACTIVITY_COMMENTS_DISLIKE_URL: 'http://api.itianluo.cn/feed_answer',
  IOS_REFRESH_START: 'itianluo://refreshstart/',
  IOS_REFRESH_FINISH: 'itianluo://refreshfinish/',
  IOS_START: 'itianluo://start',
  IOS_FINISH: 'itianluo://finish/',
  IOS_COMMENT: 'itianluo://comment/',
  IOS_PROFILE: 'itianluo://profile/',
  IOS_FOLLOWERLIST: 'itianluo://followerlist/',
  IOS_NUM: 'itianluo://num/',
  GRADES_DETAIL_URL: 'http://api2.itianluo.cn/score_my_dragon',
  GRADES_LIST_URL: 'http://api2.itianluo.cn/score_list_dragon',
  SCORE_DETAIL_URL: 'http://api2.itianluo.cn/score_detail_dragon',
  IOS_LIST: 'itianluo://list/',
  IOS_IMG: 'itianluo://img/',
  IOS_PRAISE_ID: 'itianluo://praiseId/',
  IOS_COMPLAINT_ID: 'itianluo://complaintId/',
  IOS_TASK_ID: 'itianluo://taskId/',
  IOS_SUPERVISE_ID: 'itianluo://superviseId/',
  IOS_MY_SUPERVISE_ID: 'itianluo://mySuperviseId/',
  HTML5_URL: 'http://api.itianluo.cn/addhtml',
  GET_HTML5_COMMENT_URL: 'http://api.itianluo.cn/h5_fback_list',
  HTML5_COMMENT: 'itianluo://html5comment/',
  HTML5_ID: 'itianluo://html5id/',
  IS_COMMENT: 'itianluo://iscomment/'
}
export default AppConstants
